In [2]:
from pydataset import data
import pandas as pd
import numpy as np
from env import host, user, password

In [81]:
def dataframe_splain(dataframe, use_name='sample'):
    sample_size=min(11,len(dataframe))
    print(f'{use_name.upper()} DATA')
    if sample_size == 11:
        print(dataframe.sample(10))
    else:
        print(dataframe)
    print()
    print(f'{use_name} details{str(dataframe.shape)}')
    print(dataframe.dtypes)

In [3]:
mpg = data("mpg")
data("mpg", show_doc=True)

mpg

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Fuel economy data from 1999 and 2008 for 38 popular models of car

### Description

This dataset contains a subset of the fuel economy data that the EPA makes
available on http://fueleconomy.gov. It contains only models which had a new
release every year between 1999 and 2008 - this was used as a proxy for the
popularity of the car.

### Usage

    data(mpg)

### Format

A data frame with 234 rows and 11 variables

### Details

  * manufacturer.

  * model.

  * displ. engine displacement, in litres

  * year.

  * cyl. number of cylinders

  * trans. type of transmission

  * drv. f = front-wheel drive, r = rear wheel drive, 4 = 4wd

  * cty. city miles per gallon

  * hwy. highway miles per gallon

  * fl.

  * class.

1a. On average, which manufacturer has the best miles per gallon?

In [82]:
dataframe_splain(mpg, "mpg")

MPG DATA
    manufacturer                model  displ  year  cyl       trans drv  cty  \
120      hyundai              tiburon    2.7  2008    6    auto(l4)   f   17
65         dodge  ram 1500 pickup 4wd    4.7  2008    8  manual(m6)   4   12
54         dodge    dakota pickup 4wd    4.7  2008    8    auto(l5)   4   14
73         dodge  ram 1500 pickup 4wd    5.7  2008    8    auto(l5)   4   13
164       subaru         forester awd    2.5  2008    4    auto(l4)   4   20
28     chevrolet             corvette    7.0  2008    8  manual(m6)   r   15
154       nissan       pathfinder 4wd    5.6  2008    8    auto(s5)   4   12
70         dodge  ram 1500 pickup 4wd    4.7  2008    8  manual(m6)   4    9
218   volkswagen                jetta    2.5  2008    5    auto(s6)   f   21
176       toyota          4runner 4wd    3.4  1999    6    auto(l4)   4   15

     hwy fl       class  average_mileage
120   24  r  subcompact             29.0
65    16  r      pickup             20.0
54    19  r      pickup             23.5
73    17  r      pickup             21.5
164   26  r         suv             33.0
28    24  p     2seater             27.0
154   18  p         suv             21.0
70    12  e      pickup             15.0
218   29  r     compact             35.5
176   19  r         suv             24.5

mpg details(234, 12)
manufacturer        object
model               object
displ              float64
year                 int64
cyl                  int64
trans               object
drv                 object
cty                  int64
hwy                  int64
fl                  object
class               object
average_mileage    float64
dtype: object

In [96]:
# This is wrong... go back and fix it
# If you have a groupby, you have to have an .agg
# The simplest .agg is count
# Use groupby and agg("mean")
mpg["average_mileage"] = (mpg.cty + mpg.hwy) / 2
best_average_mileage = mpg.groupby("manufacturer").count()
best_average_mileage = pd.DataFrame(mpg.groupby("manufacturer").average_mileage.agg("mean")).sort_values(by="average_mileage", ascending=False)
# best_average_mileage = mpg.sort_values(by="average_mileage", ascending=False)
best_average_mileage

              average_mileage
manufacturer
honda               28.500000
volkswagen          25.074074
hyundai             22.750000
subaru              22.428571
audi                22.027778
toyota              21.720588
pontiac             21.700000
nissan              21.346154
chevrolet           18.447368
ford                16.680000
mercury             15.625000
jeep                15.562500
dodge               15.540541
lincoln             14.166667
land rover          14.000000

1b. How many different manufacturers are there?

In [17]:
#nunique can do this, too
#mpg.manufacturer.nunique()
num_of_manufacturers = len(mpg.manufacturer.unique())
num_of_manufacturers

15

1c. How many different models are there?

In [30]:
#nunique can do this, too 
#mpg.model.nunique()
num_of_models = len(mpg.model.unique())
num_of_models

38

In [33]:
# something I was messing around with...
# models_by_manufacturer = mpg.manufacturer.value_counts()
# models_by_manufacturer

1d. Do automatic or manual cars have better miles per gallon?

In [99]:
automatic_trans = mpg[mpg.trans.str.contains("auto")]
automatic_trans

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact,22.5
9,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact,20.5
11,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact,23.0
12,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact,20.0
14,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact,21.0
16,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize,19.5
17,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize,21.0
18,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize,19.5
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv,17.0
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv,13.0
21,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv,17.0
22,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv,15.0
23,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv,14.5
25,chevrolet,corvette,5.7,1999,8,auto(l4),r,15,23,p,2seater,19.0
27,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater,20.0
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv,16.5
30,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv,12.5
31,chevrolet,k1500 tahoe 4wd,5.7,1999,8,auto(l4),4,11,15,r,suv,13.0
32,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv,15.5
33,chevrolet,malibu,2.4,1999,4,auto(l4),f,19,27,r,midsize,23.0
34,chevrolet,malibu,2.4,2008,4,auto(l4),f,22,30,r,midsize,26.0
35,chevrolet,malibu,3.1,1999,6,auto(l4),f,18,26,r,midsize,22.0
36,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize,23.5
37,chevrolet,malibu,3.6,2008,6,auto(s6),f,17,26,r,midsize,21.5
38,dodge,caravan 2wd,2.4,1999,4,auto(l3),f,18,24,r,minivan,21.0
39,dodge,caravan 2wd,3.0,1999,6,auto(l4),f,17,24,r,minivan,20.5
40,dodge,caravan 2wd,3.3,1999,6,auto(l4),f,16,22,r,minivan,19.0
41,dodge,caravan 2wd,3.3,1999,6,auto(l4),f,16,22,r,minivan,19.0
42,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,17,24,r,minivan,20.5
43,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,17,24,r,minivan,20.5
44,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,11,17,e,minivan,14.0
45,dodge,caravan 2wd,3.8,1999,6,auto(l4),f,15,22,r,minivan,18.5
46,dodge,caravan 2wd,3.8,1999,6,auto(l4),f,15,21,r,minivan,18.0
47,dodge,caravan 2wd,3.8,2008,6,auto(l6),f,16,23,r,minivan,19.5
48,dodge,caravan 2wd,4.0,2008,6,auto(l6),f,16,23,r,minivan,19.5
50,dodge,dakota pickup 4wd,3.7,2008,6,auto(l4),4,14,18,r,pickup,16.0
51,dodge,dakota pickup 4wd,3.9,1999,6,auto(l4),4,13,17,r,pickup,15.0
53,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,16.5
54,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,16.5
55,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,10.5
57,dodge,dakota pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,13.0
58,dodge,durango 4wd,3.9,1999,6,auto(l4),4,13,17,r,suv,15.0
59,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,15.0
60,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,10.5
61,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,15.0
62,dodge,durango 4wd,5.2,1999,8,auto(l4),4,11,16,r,suv,13.5
63,dodge,durango 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,15.5
64,dodge,durango 4wd,5.9,1999,8,auto(l4),4,11,15,r,suv,13.0
66,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,10.5
67,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,15.0
68,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,15.0
71,dodge,ram 1500 pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,13.0
73,dodge,ram 1500 pickup 4wd,5.7,2008,8,auto(l5),4,13,17,r,pickup,15.0
74,dodge,ram 1500 pickup 4wd,5.9,1999,8,auto(l4),4,11,15,r,pickup,13.0
75,ford,expedition 2wd,4.6,1999,8,auto(l4),r,11,17,r,suv,14.0
76,ford,expedition 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv,14.0
77,ford,expedition 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv,15.0
78,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,15.5
80,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,15.5
81,ford,explorer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv,16.0
82,ford,explorer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv,16.0
83,ford,explorer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,15.0
84,ford,f150 pickup 4wd,4.2,1999,6,auto(l4),4,14,17,r,pickup,15.5
87,ford,f150 pickup 4wd,4.6,1999,8,auto(l4),4,13,16,r,pickup,14.5
88,ford,f150 pickup 4wd,4.6,2008,8,auto(l4),4,13,17,r,pickup,15.0
89,ford,f150 pickup 4wd,5.4,1999,8,auto(l4),4,11,15,r,pickup,13.0
90,ford,f150 pickup 4wd,5.4,2008,8,auto(l4),4,13,17,r,pickup,15.0
92,ford,mustang,3.8,1999,6,auto(l4),r,18,25,r,subcompact,21.5
94,ford,mustang,4.0,2008,6,auto(l5),r,16,24,r,subcompact,20.0
95,ford,mustang,4.6,1999,8,auto(l4),r,15,21,r,subcompact,18.0
98,ford,mustang,4.6,2008,8,auto(l5),r,15,22,r,subcompact,18.5
101,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,28.0
104,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,28.0
106,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact,30.5
107,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact,30.0
109,hyundai,sonata,2.4,1999,4,auto(l4),f,18,26,r,midsize,22.0
111,hyundai,sonata,2.4,2008,4,auto(l4),f,21,30,r,midsize,25.5
113,hyundai,sonata,2.5,1999,6,auto(l4),f,18,26,r,midsize,22.0
115,hyundai,sonata,3.3,2008,6,auto(l5),f,19,28,r,midsize,23.5
116,hyundai,tiburon,2.0,1999,4,auto(l4),f,19,26,r,subcompact,22.5
119,hyundai,tiburon,2.0,2008,4,auto(l4),f,20,27,r,subcompact,23.5
120,hyundai,tiburon,2.7,2008,6,auto(l4),f,17,24,r,subcompact,20.5
123,jeep,grand cherokee 4wd,3.0,2008,6,auto(l5),4,17,22,d,suv,19.5
124,jeep,grand cherokee 4wd,3.7,2008,6,auto(l5),4,15,19,r,suv,17.0
125,jeep,grand cherokee 4wd,4.0,1999,6,auto(l4),4,15,20,r,suv,17.5
126,jeep,grand cherokee 4wd,4.7,1999,8,auto(l4),4,14,17,r,suv,15.5
127,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,10.5
128,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,14,19,r,suv,16.5
129,jeep,grand cherokee 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,15.5
130,jeep,grand cherokee 4wd,6.1,2008,8,auto(l5),4,11,14,p,suv,12.5
131,land rover,range rover,4.0,1999,8,auto(l4),4,11,15,p,suv,13.0
132,land rover,range rover,4.2,2008,8,auto(s6),4,12,18,r,suv,15.0
133,land rover,range rover,4.4,2008,8,auto(s6),4,12,18,r,suv,15.0
134,land rover,range rover,4.6,1999,8,auto(l4),4,11,15,p,suv,13.0
135,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv,14.0
136,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,16,p,suv,13.5
137,lincoln,navigator 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv,15.0
138,mercury,mountaineer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,15.5
139,mercury,mountaineer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv,16.0
140,mercury,mountaineer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv,16.0
141,mercury,mountaineer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,15.0
143,nissan,altima,2.4,1999,4,auto(l4),f,19,27,r,compact,23.0
144,nissan,altima,2.5,2008,4,auto(av),f,23,31,r,midsize,27.0
147,nissan,altima,3.5,2008,6,auto(av),f,19,26,p,midsize,22.5
148,nissan,maxima,3.0,1999,6,auto(l4),f,18,26,r,midsize,22.0
150,nissan,maxima,3.5,2008,6,auto(av),f,19,25,p,midsize,22.0
151,nissan,pathfinder 4wd,3.3,1999,6,auto(l4),4,14,17,r,suv,15.5
153,nissan,pathfinder 4wd,4.0,2008,6,auto(l5),4,14,20,p,suv,17.0
154,nissan,pathfinder 4wd,5.6,2008,8,auto(s5),4,12,18,p,suv,15.0
155,pontiac,grand prix,3.1,1999,6,auto(l4),f,18,26,r,midsize,22.0
156,pontiac,grand prix,3.8,1999,6,auto(l4),f,16,26,p,midsize,21.0
157,pontiac,grand prix,3.8,1999,6,auto(l4),f,17,27,r,midsize,22.0
158,pontiac,grand prix,3.8,2008,6,auto(l4),f,18,28,r,midsize,23.0
159,pontiac,grand prix,5.3,2008,8,auto(s4),f,16,25,p,midsize,20.5
161,subaru,forester awd,2.5,1999,4,auto(l4),4,18,24,r,suv,21.0
164,subaru,forester awd,2.5,2008,4,auto(l4),4,20,26,r,suv,23.0
165,subaru,forester awd,2.5,2008,4,auto(l4),4,18,23,p,suv,20.5
166,subaru,impreza awd,2.2,1999,4,auto(l4),4,21,26,r,subcompact,23.5
169,subaru,impreza awd,2.5,1999,4,auto(l4),4,19,26,r,subcompact,22.5
170,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,25,p,compact,22.5
171,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,27,r,compact,23.5
175,toyota,4runner 4wd,2.7,1999,4,auto(l4),4,16,20,r,suv,18.0
176,toyota,4runner 4wd,3.4,1999,6,auto(l4),4,15,19,r,suv,17.0
178,toyota,4runner 4wd,4.0,2008,6,auto(l5),4,16,20,r,suv,18.0
179,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv,15.5
181,toyota,camry,2.2,1999,4,auto(l4),f,21,27,r,midsize,24.0
183,toyota,camry,2.4,2008,4,auto(l5),f,21,31,r,midsize,26.0
184,toyota,camry,3.0,1999,6,auto(l4),f,18,26,r,midsize,22.0
186,toyota,camry,3.5,2008,6,auto(s6),f,19,28,r,midsize,23.5
187,toyota,camry solara,2.2,1999,4,auto(l4),f,21,27,r,compact,24.0
190,toyota,camry solara,2.4,2008,4,auto(s5),f,22,31,r,compact,26.5
191,toyota,camry solara,3.0,1999,6,auto(l4),f,18,26,r,compact,22.0
193,toyota,camry solara,3.3,2008,6,auto(s5),f,18,27,r,compact,22.5
194,toyota,corolla,1.8,1999,4,auto(l3),f,24,30,r,compact,27.0
195,toyota,corolla,1.8,1999,4,auto(l4),f,24,33,r,compact,28.5
198,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact,30.5
199,toyota,land cruiser wagon 4wd,4.7,1999,8,auto(l4),4,11,15,r,suv,13.0
200,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv,15.5
202,toyota,toyota tacoma 4wd,2.7,1999,4,auto(l4),4,16,20,r,pickup,18.0
205,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup,17.0
207,toyota,toyota tacoma 4wd,4.0,2008,6,auto(l5),4,16,20,r,pickup,18.0
209,volkswagen,gti,2.0,1999,4,auto(l4),f,19,26,r,compact,22.5
211,volkswagen,gti,2.0,2008,4,auto(s6),f,22,29,p,compact,25.5
215,volkswagen,jetta,2.0,1999,4,auto(l4),f,19,26,r,compact,22.5
216,volkswagen,jetta,2.0,2008,4,auto(s6),f,22,29,p,compact,25.5
218,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact,25.0
220,volkswagen,jetta,2.8,1999,6,auto(l4),f,16,23,r,compact,19.5
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,35.0
225,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact,22.5
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact,24.5
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize,23.5
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,23.5
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,21.0
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,21.5

In [100]:
#automatic_trans.sort_values(by="average_mileage", ascending=False)
automatic_trans_mean = round(automatic_trans.average_mileage.mean())
automatic_trans_mean

19

In [101]:
manual_trans = mpg[mpg.trans.str.contains("man")]
manual_trans_mean = round(manual_trans.average_mileage.mean())
manual_trans_mean

22

In [74]:
#manual_trans.average_mileage.value_counts(ascending=False)

2. Joining and Merging

Copy the users and roles dataframes from the examples above. What do you think a right join would look like? An outer join? What happens if you drop the foreign keys from the dataframes and try to merge them?

In [77]:
# create dataframes
users = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['bob', 'joe', 'sally', 'adam', 'jane', 'mike'],
    'role_id': [1, 2, 3, 3, np.nan, np.nan]
})

roles = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['admin', 'author', 'reviewer', 'commenter']
})

In [78]:
# merge using how="right" We accept nulls/NaNs from the right table
pd.merge(
    users.rename(columns={"id": "user_id", "name": "username"}),
    roles.rename(columns={"name": "role_name"}),
    left_on="role_id", right_on="id", how="right")

   user_id username  role_id  id  role_name
0      1.0      bob      1.0   1      admin
1      2.0      joe      2.0   2     author
2      3.0    sally      3.0   3   reviewer
3      4.0     adam      3.0   3   reviewer
4      NaN      NaN      NaN   4  commenter

In [79]:
# merge using how="outer"
pd.merge(
    users.rename(columns={"id": "user_id", "name": "username"}),
    roles.rename(columns={"name": "role_name"}),
    left_on="role_id", right_on="id", how="outer")

   user_id username  role_id   id  role_name
0      1.0      bob      1.0  1.0      admin
1      2.0      joe      2.0  2.0     author
2      3.0    sally      3.0  3.0   reviewer
3      4.0     adam      3.0  3.0   reviewer
4      5.0     jane      NaN  NaN        NaN
5      6.0     mike      NaN  NaN        NaN
6      NaN      NaN      NaN  4.0  commenter

In [ ]:
# merge dropping foreign keys
pd.merge(
    users.rename(columns={"id": "user_id", "name": "username"}),
    roles.rename(columns={"name": "role_name"}),
    left_on="role_id", right_on="id", how="right")

3. Getting data from SQL databases

    Create a function named get_db_url. It should accept a username, hostname, password, and database name and return a url formatted like in the examples in this lesson.

    Write the code necessary to create a cross tabulation of the number of titles by department. (Hint: this will involve a combination of SQL and python/pandas code)

In [3]:
# create a function that produces the necessary connection string for communication
# between a SQL query and Pandas
def get_db_url(username, hostname, password, db_name):
    return f"mysql+pymysql://{user}:{password}@{host}/{db_name}"

-Use your function to obtain a connection to the employees database.

In [11]:
url = get_db_url(user, host, password, "employees")

-Once you have successfully run a query:

In [12]:
df_employees = pd.read_sql('SELECT * FROM employees', url)

-Intentionally make a typo in the database url. What kind of error message do you see?

-Intentionally make an error in your SQL query. What does the error message look like?

-Read the employees and titles tables into two separate dataframes

In [14]:
df_titles = pd.read_sql("SELECT * FROM titles", url)
df_titles.head()

   emp_no            title   from_date     to_date
0   10001  Senior Engineer  1986-06-26  9999-01-01
1   10002            Staff  1996-08-03  9999-01-01
2   10003  Senior Engineer  1995-12-03  9999-01-01
3   10004         Engineer  1986-12-01  1995-12-01
4   10004  Senior Engineer  1995-12-01  9999-01-01

-Visualize the number of employees with each title.

In [17]:
sql ="""
SELECT title, count(*) as number
FROM titles
GROUP  BY title;
""" 
pd.read_sql(sql, url)

                title  number
0  Assistant Engineer   15128
1            Engineer  115003
2             Manager      24
3     Senior Engineer   97750
4        Senior Staff   92853
5               Staff  107391
6    Technique Leader   15159

In [16]:
df_titles.groupby("title").count().emp_no

title
Assistant Engineer     15128
Engineer              115003
Manager                   24
Senior Engineer        97750
Senior Staff           92853
Staff                 107391
Technique Leader       15159
Name: emp_no, dtype: int64

-Join the employees and titles dataframes together.

-Visualize how frequently employees change titles.

-For each title, find the hire date of the employee that was hired most recently with that title.

-Write the code necessary to create a cross tabulation of the number of titles by department. (Hint: this will involve a combination of SQL and python/pandas code)