In [1]:
import numpy as np
from matplotlib import pyplot as plt
import csv
from collections import Counter
import pandas as pd

#plt.style.use("fivethirtyeight")
df = pd.read_csv("school_census_data_18.csv")#, header = 0, usecols = ["Gender", "Handed", "Superpower"])

df.head()

,Country,Region,DataYear,ClassGrade,Gender,Ageyears,Handed,Height_cm,Footlength_cm,Armspan_cm,...,Watching_TV_Hours,Paid_Work_Hours,Work_At_Home_Hours,Schoolwork_Pressure,Planned_Education_Level,Favorite_Music,Superpower,Preferred_Status,Role_Model_Type,Charity_Donation
0,USA,TX,2018,12,Female,17.0,Right-Handed,152,22.5,24,...,0.0,35.0,1.0,Very little,Graduate degree,Rap/Hip hop,Invisibility,Happy,Business person,Environment
1,USA,TN,2018,12,Male,18.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USA,CO,2018,12,Female,17.0,Ambidextrous,164cm,22cm,160cm,...,6.0,2.0,2.0,Some,Graduate degree,Rap/Hip hop,Invisibility,Happy,Friend,International aid
3,USA,ID,2018,12,Male,23.0,Right-Handed,171.5,21.6,162.5,...,2.0,0.0,8.0,A lot,Graduate degree,Gospel,Freeze time,Happy,Relative,Religious
4,USA,NC,2018,12,Female,17.0,Right-Handed,136,26,54,...,0.0,2.0,2.0,A lot,Undergraduate degree,Rap/Hip hop,Freeze time,Happy,Relative,International aid

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 60 columns):
Country                             100 non-null object
Region                              100 non-null object
DataYear                            100 non-null int64
ClassGrade                          100 non-null int64
Gender                              99 non-null object
Ageyears                            99 non-null float64
Handed                              97 non-null object
Height_cm                           95 non-null object
Footlength_cm                       94 non-null object
Armspan_cm                          93 non-null object
Languages_spoken                    97 non-null float64
Travel_to_School                    98 non-null object
Travel_time_to_School               98 non-null object
Reaction_time                       97 non-null float64
Score_in_memory_game                96 non-null float64
Favourite_physical_activity         96 non-null object
Importance_reducing_pollution       94 non-null float64
Importance_recycling_rubbish        94 non-null float64
Importance_conserving_water         93 non-null float64
Importance_saving_energy            93 non-null float64
Importance_owning_computer          93 non-null float64
Importance_Internet_access          93 non-null float64
Left_Footlength_cm                  90 non-null float64
Longer_foot                         92 non-null object
Index_Fingerlength_mm               88 non-null float64
Ring_Fingerlength_mm                88 non-null float64
Longer_Finger_Lefthand              89 non-null object
Birth_month                         95 non-null object
Favorite_Season                     95 non-null object
Allergies                           95 non-null object
Vegetarian                          95 non-null object
Favorite_Food                       95 non-null object
Beverage                            95 non-null object
Favorite_School_Subject             95 non-null object
Sleep_Hours_Schoolnight             94 non-null float64
Sleep_Hours_Non_Schoolnight         94 non-null float64
Home_Occupants                      94 non-null float64
Home_Internet_Access                92 non-null object
Communication_With_Friends          93 non-null object
Text_Messages_Sent_Yesterday        94 non-null float64
Text_Messages_Received_Yesterday    94 non-null float64
Hanging_Out_With_Friends_Hours      94 non-null float64
Talking_On_Phone_Hours              94 non-null float64
Doing_Homework_Hours                94 non-null float64
Doing_Things_With_Family_Hours      94 non-null float64
Outdoor_Activities_Hours            94 non-null float64
Video_Games_Hours                   94 non-null float64
Social_Websites_Hours               94 non-null float64
Texting_Messaging_Hours             92 non-null float64
Computer_Use_Hours                  94 non-null float64
Watching_TV_Hours                   93 non-null float64
Paid_Work_Hours                     93 non-null float64
Work_At_Home_Hours                  93 non-null float64
Schoolwork_Pressure                 93 non-null object
Planned_Education_Level             94 non-null object
Favorite_Music                      93 non-null object
Superpower                          93 non-null object
Preferred_Status                    94 non-null object
Role_Model_Type                     94 non-null object
Charity_Donation                    94 non-null object
dtypes: float64(30), int64(2), object(28)
memory usage: 47.0+ KB

In [3]:
df.isnull().sum()

Country                              0
Region                               0
DataYear                             0
ClassGrade                           0
Gender                               1
Ageyears                             1
Handed                               3
Height_cm                            5
Footlength_cm                        6
Armspan_cm                           7
Languages_spoken                     3
Travel_to_School                     2
Travel_time_to_School                2
Reaction_time                        3
Score_in_memory_game                 4
Favourite_physical_activity          4
Importance_reducing_pollution        6
Importance_recycling_rubbish         6
Importance_conserving_water          7
Importance_saving_energy             7
Importance_owning_computer           7
Importance_Internet_access           7
Left_Footlength_cm                  10
Longer_foot                          8
Index_Fingerlength_mm               12
Ring_Fingerlength_mm                12
Longer_Finger_Lefthand              11
Birth_month                          5
Favorite_Season                      5
Allergies                            5
Vegetarian                           5
Favorite_Food                        5
Beverage                             5
Favorite_School_Subject              5
Sleep_Hours_Schoolnight              6
Sleep_Hours_Non_Schoolnight          6
Home_Occupants                       6
Home_Internet_Access                 8
Communication_With_Friends           7
Text_Messages_Sent_Yesterday         6
Text_Messages_Received_Yesterday     6
Hanging_Out_With_Friends_Hours       6
Talking_On_Phone_Hours               6
Doing_Homework_Hours                 6
Doing_Things_With_Family_Hours       6
Outdoor_Activities_Hours             6
Video_Games_Hours                    6
Social_Websites_Hours                6
Texting_Messaging_Hours              8
Computer_Use_Hours                   6
Watching_TV_Hours                    7
Paid_Work_Hours                      7
Work_At_Home_Hours                   7
Schoolwork_Pressure                  7
Planned_Education_Level              6
Favorite_Music                       7
Superpower                           7
Preferred_Status                     6
Role_Model_Type                      6
Charity_Donation                     6
dtype: int64

In [6]:
df.DataYear.value_counts()

2018    100
Name: DataYear, dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 0 to 99
Data columns (total 60 columns):
Country                             75 non-null object
Region                              75 non-null object
DataYear                            75 non-null int64
ClassGrade                          75 non-null int64
Gender                              75 non-null object
Ageyears                            75 non-null float64
Handed                              75 non-null object
Height_cm                           75 non-null object
Footlength_cm                       75 non-null object
Armspan_cm                          75 non-null object
Languages_spoken                    75 non-null float64
Travel_to_School                    75 non-null object
Travel_time_to_School               75 non-null object
Reaction_time                       75 non-null float64
Score_in_memory_game                75 non-null float64
Favourite_physical_activity         75 non-null object
Importance_reducing_pollution       75 non-null float64
Importance_recycling_rubbish        75 non-null float64
Importance_conserving_water         75 non-null float64
Importance_saving_energy            75 non-null float64
Importance_owning_computer          75 non-null float64
Importance_Internet_access          75 non-null float64
Left_Footlength_cm                  75 non-null float64
Longer_foot                         75 non-null object
Index_Fingerlength_mm               75 non-null float64
Ring_Fingerlength_mm                75 non-null float64
Longer_Finger_Lefthand              75 non-null object
Birth_month                         75 non-null object
Favorite_Season                     75 non-null object
Allergies                           75 non-null object
Vegetarian                          75 non-null object
Favorite_Food                       75 non-null object
Beverage                            75 non-null object
Favorite_School_Subject             75 non-null object
Sleep_Hours_Schoolnight             75 non-null float64
Sleep_Hours_Non_Schoolnight         75 non-null float64
Home_Occupants                      75 non-null float64
Home_Internet_Access                75 non-null object
Communication_With_Friends          75 non-null object
Text_Messages_Sent_Yesterday        75 non-null float64
Text_Messages_Received_Yesterday    75 non-null float64
Hanging_Out_With_Friends_Hours      75 non-null float64
Talking_On_Phone_Hours              75 non-null float64
Doing_Homework_Hours                75 non-null float64
Doing_Things_With_Family_Hours      75 non-null float64
Outdoor_Activities_Hours            75 non-null float64
Video_Games_Hours                   75 non-null float64
Social_Websites_Hours               75 non-null float64
Texting_Messaging_Hours             75 non-null float64
Computer_Use_Hours                  75 non-null float64
Watching_TV_Hours                   75 non-null float64
Paid_Work_Hours                     75 non-null float64
Work_At_Home_Hours                  75 non-null float64
Schoolwork_Pressure                 75 non-null object
Planned_Education_Level             75 non-null object
Favorite_Music                      75 non-null object
Superpower                          75 non-null object
Preferred_Status                    75 non-null object
Role_Model_Type                     75 non-null object
Charity_Donation                    75 non-null object
dtypes: float64(30), int64(2), object(28)
memory usage: 35.7+ KB